SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE room;
SET REFERENTIAL_INTEGRITY TRUE;
ALTER TABLE room ALTER COLUMN id RESTART WITH 1;

INSERT INTO room(id, number, suite, available) VALUES(1, '001', false, true);